### ISSUE TITLE
下停止命令後，沒辦法完整關閉

### ISSUE THREAD

**Issue by minexo79** [cuiguangzhen/FFmpegPlayRtsp#1]
作者你好：
我嘗試在程式中加入停止按鈕，並且使用`CancellationTokenSource`結束整個Thread與`FFmpegHelp.ShowBitmap`的運作。
```cs
private unsafe void DeCoding()
{
    if (cts.IsCancellationRequested)
        return;

    // do smth...
}
```

在前一到二次的操作中可以完整關閉撥放，但之後卻沒辦法讓`FFmpegHelp.cs`內的`while`迴圈沒辦法跳出，導致Thread內的`FFmpegHelp.ShowBitmap`事件還在執行。
我有嘗試把`FFmpegHelp.cs`內的`while`迴圈改成`do {} while(CanRun)`迴圈，但問題依舊沒有改變。

停止函數：
```cs
void Stop()
{
    Console.WriteLine("---------Stop Stream!!---------");

    cts.Cancel();
    cts.Dispose();

    ClassHelp.Instance.FFmpegHelp?.Stop();
    ClassHelp.Instance.FFmpegHelp = null;

    thPlayer?.DisableComObjectEagerCleanup();
    thPlayer = null;
}
```

**Comment by cuiguangzhen** [comment]
你可以尝试在停止Thread和ClassHelp.Instance.FFmpegHelp?.Stop();之间增加一个thread sleep的操作

从 Windows 版邮件发送

发件人: XOT
发送时间: 2023年9月4日 17:00
主题: [cuiguangzhen/FFmpegPlayRtsp] 下停止命令後，沒辦法完整關閉 (Issue #1)

作者你好：
我嘗試在程式中加入停止按鈕，並且使用CancellationTokenSource結束整個Thread與FFmpegHelp.ShowBitmap的運作。
private unsafe void DeCoding()
{
    if (cts.IsCancellationRequested)
        return;

    // do smth...
}
在前一到二次的操作中可以完整關閉撥放，但之後卻沒辦法讓FFmpegHelp.cs內的while迴圈沒辦法跳出，導致Thread內的FFmpegHelp.ShowBitmap事件還在執行。
停止函數：
void Stop()
{
    Console.WriteLine("---------Stop Stream!!---------");

    cts.Cancel();
    cts.Dispose();

    ClassHelp.Instance.FFmpegHelp?.Stop();
    ClassHelp.Instance.FFmpegHelp   = null;

    thPlayer?.DisableComObjectEagerCleanup();
    thPlayer = null;
}

**Comment by minexo79** [comment]
可以正常關閉了，謝謝
